version: "3.7"
services:
  nuxt:
    image: fmb
    depends_on:
      - postgres
    container_name: dev
    restart: unless-stopped
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15.3-alpine
    container_name: devdb
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  thumbor:
    depends_on:
      - postgres
    image: minimalcompact/thumbor:6.7.5
    restart: unless-stopped
    container_name: devimg
    ports:
      - "8888:80"
    environment:
      - UPLOAD_ENABLED=True
    volumes:
      - ./thumbor:/thumbor/images
