version: "3.7"
services:
  # nuxt:
  #   image: fmb
  #   depends_on:
  #     - postgres
  #   container_name: dev
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #     - "3001:3001"
  postgres:
    image: postgres:15.3-alpine
    container_name: devdb
    restart: unless-stopped
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  devmedia:
    depends_on:
      - postgres
    image: easypix
    restart: unless-stopped
    container_name: devmedia
    ports:
      - "8888:8888"
    volumes:
      - ./thumbor:/go/bin/uploads
